#!/bin/bash 	 
set -x
#$ -N scale 	# Job Name
#$ -pe 12way 12 	# Requests 12 tasks/node
#$ -q development 	# Queue normal or development
#$ -l h_rt=1:00:00 	# Run time (hh:mm:ss) 
#$ -V 	#Inherit the submission environment
#$ -j y 	# Combine stderr and stdout
#$ -o /work/03201/spann/blood/csv/$JOB_NAME.o$JOB_ID 	# Name of the output file 
#$ -M spann@che.utexas.edu	# Address for email notification
#$ -m be 	# Email at Begin and End of job

cd ${WORK}/blood/wall0/
#cp ${HOME}/gblood/vessim/vchannel ./
#cp ${WORK}/blood/D/restart000000.dat ./
#cp -r ${WORK}/blood/Input ./
ibrun ./vchannel	# Run the MPI executable
